//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Database.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddedDate.
        /// </summary>
        internal static string Column_AddedDate {
            get {
                return ResourceManager.GetString("Column_AddedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameName.
        /// </summary>
        internal static string Column_GameName {
            get {
                return ResourceManager.GetString("Column_GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Column_Key {
            get {
                return ResourceManager.GetString("Column_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OwnedStatus.
        /// </summary>
        internal static string Column_OwnedStatus {
            get {
                return ResourceManager.GetString("Column_OwnedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        internal static string Column_PC {
            get {
                return ResourceManager.GetString("Column_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayedStatus.
        /// </summary>
        internal static string Column_PlayedStatus {
            get {
                return ResourceManager.GetString("Column_PlayedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS3.
        /// </summary>
        internal static string Column_PS3 {
            get {
                return ResourceManager.GetString("Column_PS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS4.
        /// </summary>
        internal static string Column_PS4 {
            get {
                return ResourceManager.GetString("Column_PS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSVita.
        /// </summary>
        internal static string Column_PSVita {
            get {
                return ResourceManager.GetString("Column_PSVita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Column_Value {
            get {
                return ResourceManager.GetString("Column_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchemaVersion.
        /// </summary>
        internal static string Settings_SchemaVersion {
            get {
                return ResourceManager.GetString("Settings_SchemaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string TableName_Games {
            get {
                return ResourceManager.GetString("TableName_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GamesBackup.
        /// </summary>
        internal static string TableName_GamesBackup {
            get {
                return ResourceManager.GetString("TableName_GamesBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TableName_Settings {
            get {
                return ResourceManager.GetString("TableName_Settings", resourceCulture);
            }
        }
    }
}
